### ISSUE TITLE
Species dropped through rollup

### ISSUE THREAD

**Issue by JoseeRousseau** [CornellLabofOrnithology/auk#31]
Double-checking the results from running auk_rollup() on a sample EBD dataset (the sample available at https://ebird.org/data/download), I realized that all the Downy Woodpeckers were dropped completely in the resulting data frame.  The functionality of auk_rollup() seems to work for all the other category/records present in the sample.

    f_in_NoRollUp <- "./ebd_US-AL-101_201801_201801_relMay-2018.txt" %>%
    		read_ebd(rollup = FALSE)
    # apply roll up
    ebd_ru <- auk_rollup(f_in_NoRollUp)

    # without rollup, there are nine observations
    f_in_NoRollUp %>%
    	filter(common_name == "Downy Woodpecker") %>%
    	select(checklist_id, category, common_name, subspecies_common_name,
    				 observation_count)
    # with rollup, they have been combined .... why did it remove all the downy woodpecker?
    ebd_ru %>%
    	filter(common_name == "Downy Woodpecker") %>%
    	select(checklist_id, category, common_name, observation_count)

**Comment by mstrimas** [comment]
Hi Josee, thanks for the bug report! I've been trying to replicate the issue you're having, but am not having any luck; I get 9 observations whether or not `auk_rollup()` is called. It looks like you're using data downloaded via the custom download form, could you post the download link you were emailed here? Thanks!

**Comment by JoseeRousseau** [comment]
I actually used the EBD sample directly accessible at https://ebird.org/data/download (the top blue arrow; downloaded 2 days ago). Let me know if you want me to send you the file (and how; the file is less than 1 mb).

**Comment by mstrimas** [comment]
Oh, I see what's happened, that EBD sample file is outdated, from last May. Between then and now, the Downy Woodpecker's scientific name has changed from _Picoides pubescens_ to _Dryobates pubescens_. By default, `auk` always uses the most current taxonomy, which doesn't include _Picoides pubescens_. If you're using real data (i.e. not the sample), you should be fine. But, note that you can always, use older versions of the taxonomy, e.g. in this case:
```
ebd_ru <- auk_rollup(f_in_NoRollUp, taxonomy_version = 2017)
```

More generally, the taxonomy is always updated once a year, in August. So, keep your eye out for an updated version of `auk` in the next month or so that will include the new taxonomy. And, any EBD files downloaded after August will be based on this new taxonomy.

**Comment by JoseeRousseau** [comment]
Glad you found the problem (and glad auk_rollup itself did not have a bug ;-). Good to know about taxonomy_version.  Thanks!!
