### ISSUE TITLE
Filter on months across a range of years?

### ISSUE THREAD

**Issue by nmtarr** [CornellLabofOrnithology/auk#51]
Is it possible to somehow use auk_date() to select records only from certain months AND certain years?  For example, only return records from May and June of years between 2015 to 2020?  

I tried using two calls of auk_date() in succession but that didn't work.  Any help would be appreciated.

**Comment by mstrimas** [comment]
Unfortunately that's not really possible given the way auk works under the hood. In this case, I'd pick whichever filter you think will result in a smaller data set, run that one, then do a second round of filtering. It's likely that the second round could be done directly in R with `dplyr` since the result of the first filtering will hopefully be small enough that you can read it into R as a data frame.

**Comment by nmtarr** [comment]
Sounds good.  Thanks for auk!
